# coding=utf-8
import os
SECRET_KEY = os.urandom(24)

DEBUG = True

HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'zlbbs'
USERNAME = 'root'
PASSWORD = 'coursedev'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = False

# PERMANENT_SESSION_LIFETIME = '1800'
CMS_USER_ID = 'SFASDFSAFASDFSAF'